name: Provision Azure Monitoring Agent
on:
  push:
    # branches:
    # - main
  workflow_dispatch:

jobs:
  pre-requisites:
    name: 'Setup'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      uamiName: ama-uami-01
      uamiResourceGroup: ama-rg-01
      uamiLocation: eastus2
      uamiRoleAssignmentVmContrib: "Virtual Machine Contributor"
      uamiRoleAssignmentLogAnalyticsContrib: "Log Analytics Contributor"
      uamiRoleAssignmentArcContrib: "Azure Arc Connected Resource Administrator"

    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    # Authenticate to Azure tenant using the Azure login action
    - name: Create Managed Identity
      uses: Azure/login@v1
      with:
       creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
    
      # Create a user assigned managed identity
    - name: Create Managed Identity
      uses: Azure/CLI@v1
      with: 
        azcliversion: 2.49.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/az-scripts/createAndAssingUami.sh
          $GITHUB_WORKSPACE/az-scripts/createAndAssingUami.sh 
      



