# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/github-actions?view=azure-devops
name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          adoProject: https://dev.azure.com/autocloudarc/tfPrjReveiw01
          adoPipeline: tfPrjReveiw02

        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1.2
          with:
            # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
            azure-devops-project-url: $adoProject
            # Name of the Azure Pipline to be triggered
            azure-pipeline-name: $adoPipeline
            # Set/Overwrite pipeline variables
            # azure-pipeline-variables: # optional
            # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
            azure-devops-token: $AZURE_DEVOPS_TOKEN